# Generated by Django 2.1.4 on 2018-12-22 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('hashtag', models.CharField(default='', max_length=200)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seq2SeqPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('hashtag', models.CharField(default='', max_length=200)),
                ('text', models.TextField()),
                ('abstract', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weiboID', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='seq2seqpost',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo.Weibo'),
        ),
        migrations.AddField(
            model_name='post',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weibo.Weibo'),
        ),
    ]
